version: '3.9'
services:
  webserver:
    build: .
    ports:
      - "80:80"
    networks:
      - mynet
    volumes:
      - myvol:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - mynet
    volumes:
      - db_vol:/var/lib/mysql

networks:
  mynet:
    driver: bridge

volumes:
  myvol:
  db_vol: